name: northwind-database-with-mariadb
recipe: lamp

config:
  via: apache:2.4
  database: mariadb
  composer_version: '2'
  php: '8.3'
  xdebug: true
  webroot: web
  config:
    php: .vscode/php.ini

services:
  phpmyadmin:
    type: phpmyadmin

env_file:
  - .vscode/lando.env

# Lando version.
version: 3.20.8
